const bancoPalavras = {
    comida: [
        { palavra: "Pizza", dica: "Itália" },
        { palavra: "Hambúrguer", dica: "Lanche" },
        { palavra: "Sushi", dica: "Japão" },
        { palavra: "Chocolate", dica: "Doce" },
        { palavra: "Arroz", dica: "Grão" },
        { palavra: "Sorvete", dica: "Gelado" },
        { palavra: "Melancia", dica: "Fruta" },
        { palavra: "Pastel", dica: "Feira" },
        { palavra: "Coxinha", dica: "Salgado" },
        { palavra: "Pipoca", dica: "Cinema" },
        { palavra: "Pão", dica: "Massa" },
        { palavra: "Churrasco", dica: "Carne" },
        { palavra: "Açaí", dica: "Roxo" },
        { palavra: "Bolo", dica: "Festa" },
        { palavra: "Queijo", dica: "Leite" },
        { palavra: "Lasanha", dica: "Massa" },
        { palavra: "Feijoada", dica: "Feijão" },
        { palavra: "Batata Frita", dica: "Crocante" },
        { palavra: "Macarronada", dica: "Molho" },
        { palavra: "Estrogonofe", dica: "Frango" },
        { palavra: "Panqueca", dica: "Frigideira" },
        { palavra: "Tapioca", dica: "Mandioca" },
        { palavra: "Brigadeiro", dica: "Chocolate" },
        { palavra: "Pudim", dica: "Calda" },
        { palavra: "Gelatina", dica: "Gelada" },
        { palavra: "Salada", dica: "Verde" },
        { palavra: "Sopa", dica: "Caldo" },
        { palavra: "Omelete", dica: "Ovo" },
        { palavra: "Sanduíche", dica: "Pão" },
        { palavra: "Waffle", dica: "Mel" },
        { palavra: "Donut", dica: "Rosquinha" },
        { palavra: "Croissant", dica: "França" },
        { palavra: "Guacamole", dica: "Abacate" },
        { palavra: "Yakisoba", dica: "Macarrão" },
        { palavra: "Paella", dica: "Espanha" },
        { palavra: "Biscoito", dica: "Crocante" },
        { palavra: "Torrada", dica: "Torrada" },
        { palavra: "Panetone", dica: "Natal" },
        { palavra: "Pão de Queijo", dica: "Minas" },
        { palavra: "Farofa", dica: "Seca" },
        { palavra: "Empada", dica: "Forno" },
        { palavra: "Quibe", dica: "Árabe" },
        { palavra: "Esfiha", dica: "Carne" },
        { palavra: "Churros", dica: "Doce" },
        { palavra: "Crepe", dica: "Fino" },
        { palavra: "Iogurte", dica: "Líquido" },
        { palavra: "Fondue", dica: "Inverno" },
        { palavra: "Risoto", dica: "Arroz" },
        { palavra: "Nugget", dica: "Frango" },
        { palavra: "Cuscuz", dica: "Milho" },
        { palavra: "Beijinho", dica: "Coco" },
        { palavra: "Torta de Limão", dica: "Cítrica" }
    ],
    famosos: [
        { palavra: "Neymar", dica: "Futebol" },
        { palavra: "Anitta", dica: "Música" },
        { palavra: "Silvio Santos", dica: "Televisão" },
        { palavra: "Faustão", dica: "Televisão" },
        { palavra: "Cristiano Ronaldo", dica: "Portugal" },
        { palavra: "Beyoncé", dica: "Cantora" },
        { palavra: "Michael Jackson", dica: "Pop" },
        { palavra: "Lionel Messi", dica: "Argentina" },
        { palavra: "Lady Gaga", dica: "Pop" },
        { palavra: "Keanu Reeves", dica: "Cinema" },
        { palavra: "Leonardo DiCaprio", dica: "Ator" },
        { palavra: "Ayrton Senna", dica: "Corrida" },
        { palavra: "Taylor Swift", dica: "Cantora" },
        { palavra: "Will Smith", dica: "Hollywood" },
        { palavra: "Angelina Jolie", dica: "Atriz" },
        { palavra: "Brad Pitt", dica: "Ator" },
        { palavra: "Tom Cruise", dica: "Ação" },
        { palavra: "Rihanna", dica: "Música" },
        { palavra: "Eminem", dica: "Rap" },
        { palavra: "Shakira", dica: "Pop" },
        { palavra: "Ivete Sangalo", dica: "Axé" },
        { palavra: "Luan Santana", dica: "Sertanejo" },
        { palavra: "Gusttavo Lima", dica: "Sertanejo" },
        { palavra: "Xuxa", dica: "Infantil" },
        { palavra: "Angélica", dica: "Televisão" },
        { palavra: "Pelé", dica: "Futebol" },
        { palavra: "Maradona", dica: "Futebol" },
        { palavra: "Elon Musk", dica: "Foguete" },
        { palavra: "Bill Gates", dica: "Software" },
        { palavra: "Steve Jobs", dica: "Celular" },
        { palavra: "Albert Einstein", dica: "Física" },
        { palavra: "William Shakespeare", dica: "Teatro" },
        { palavra: "Machado de Assis", dica: "Livros" },
        { palavra: "Billie Eilish", dica: "Cantora" },
        { palavra: "Bruna Marquezine", dica: "Atriz" },
        { palavra: "Whindersson Nunes", dica: "Comédia" },
        { palavra: "Casimiro", dica: "Internet" },
        { palavra: "Robert Downey Jr", dica: "Cinema" },
        { palavra: "Dwayne Johnson", dica: "Ator" },
        { palavra: "Selena Gomez", dica: "Cantora" },
        { palavra: "Justin Bieber", dica: "Música" },
        { palavra: "Madonna", dica: "Pop" },
        { palavra: "Freddie Mercury", dica: "Rock" },
        { palavra: "Johnny Depp", dica: "Ator" },
        { palabra: "Morgan Freeman", dica: "Cinema" },
        { palavra: "Jackie Chan", dica: "Luta" },
        { palavra: "Marta", dica: "Futebol" },
        { palavra: "Lewis Hamilton", dica: "Corrida" },
        { palavra: "Zeca Pagodinho", dica: "Samba" },
        { palavra: "Alok", dica: "Música" },
        { palavra: "Ludmilla", dica: "Funk" },
        { palavra: "Ariana Grande", dica: "Pop" }
    ],
    objetos: [
        { palavra: "Celular", dica: "Tela" },
        { palavra: "Chave", dica: "Fechadura" },
        { palavra: "Relógio", dica: "Hora" },
        { palavra: "Caneta", dica: "Tinta" },
        { palavra: "Cadeira", dica: "Assento" },
        { palavra: "Garrafa", dica: "Líquido" },
        { palavra: "Óculos", dica: "Lente" },
        { palavra: "Mochila", dica: "Costas" },
        { palavra: "Caderno", dica: "Papel" },
        { palavra: "Sapato", dica: "Pé" },
        { palavra: "Guarda-chuva", dica: "Chuva" },
        { palavra: "Controle Remoto", dica: "Televisão" },
        { palavra: "Carteira", dica: "Dinheiro" },
        { palavra: "Espelho", dica: "Vidro" },
        { palavra: "Fone de Ouvido", dica: "Áudio" },
        { palavra: "Televisão", dica: "Imagem" },
        { palavra: "Computador", dica: "Teclado" },
        { palavra: "Livro", dica: "Leitura" },
        { palavra: "Luminária", dica: "Luz" },
        { palavra: "Almofada", dica: "Sofá" },
        { palavra: "Toalha", dica: "Banho" },
        { palavra: "Escova de Dentes", dica: "Boca" },
        { palavra: "Pente", dica: "Cabelo" },
        { palavra: "Sabonete", dica: "Limpeza" },
        { palavra: "Tesoura", dica: "Corte" },
        { palavra: "Martelo", dica: "Ferramenta" },
        { palavra: "Faca", dica: "Corte" },
        { palavra: "Garfo", dica: "Metal" },
        { palavra: "Prato", dica: "Louça" },
        { palavra: "Copo", dica: "Vidro" },
        { palavra: "Panela", dica: "Metal" },
        { palavra: "Vassoura", dica: "Chão" },
        { palavra: "Balde", dica: "Plástico" },
        { palavra: "Cama", dica: "Quarto" },
        { palavra: "Travesseiro", dica: "Cama" },
        { palavra: "Sofá", dica: "Sala" },
        { palavra: "Mesa", dica: "Madeira" },
        { palavra: "Tapete", dica: "Chão" },
        { palavra: "Cortina", dica: "Tecido" },
        { palavra: "Ventilador", dica: "Vento" },
        { palavra: "Geladeira", dica: "Frio" },
        { palavra: "Micro-ondas", dica: "Calor" },
        { palavra: "Ferro de Passar", dica: "Roupa" },
        { palavra: "Maleta", dica: "Couro" },
        { palavra: "Grampeador", dica: "Metal" },
        { palavra: "Calculadora", dica: "Números" },
        { palavra: "Carregador", dica: "Bateria" },
        { palavra: "Isqueiro", dica: "Fogo" },
        { palavra: "Cadeado", dica: "Metal" },
        { palavra: "Anel", dica: "Dedo" },
        { palavra: "Chave de Fenda", dica: "Ferramenta" },
        { palavra: "Lanterna", dica: "Luz" }
    ],
    profissao: [
        { palavra: "Médico", dica: "Saúde" },
        { palavra: "Professor", dica: "Ensino" },
        { palavra: "Policial", dica: "Lei" },
        { palavra: "Bombeiro", dica: "Fogo" },
        { palavra: "Advogado", dica: "Defesa" },
        { palavra: "Engenheiro", dica: "Cálculo" },
        { palavra: "Chef de Cozinha", dica: "Culinária" },
        { palavra: "Dentista", dica: "Dente" },
        { palavra: "Astronauta", dica: "Espaço" },
        { palavra: "Veterinário", dica: "Animal" },
        { palavra: "Pintor", dica: "Tinta" },
        { palavra: "Programador", dica: "Código" },
        { palavra: "Fotógrafo", dica: "Câmera" },
        { palavra: "Músico", dica: "Som" },
        { palavra: "Motorista", dica: "Carro" },
        { palavra: "Arquiteto", dica: "Desenho" },
        { palavra: "Jornalista", dica: "Notícia" },
        { palavra: "Enfermeiro", dica: "Cuidado" },
        { palavra: "Psicólogo", dica: "Terapia" },
        { palavra: "Farmacêutico", dica: "Remédio" },
        { palavra: "Ator", dica: "Teatro" },
        { palavra: "Dançarino", dica: "Dança" },
        { palavra: "Piloto de Avião", dica: "Voo" },
        { palavra: "Comissário de Bordo", dica: "Avião" },
        { palavra: "Marinheiro", dica: "Navio" },
        { palavra: "Militar", dica: "Farda" },
        { palavra: "Eletricista", dica: "Fio" },
        { palavra: "Encanador", dica: "Cano" },
        { palavra: "Pedreiro", dica: "Obra" },
        { palavra: "Carpinteiro", dica: "Madeira" },
        { palavra: "Mecânico", dica: "Motor" },
        { palavra: "Carteiro", dica: "Carta" },
        { palavra: "Gari", dica: "Rua" },
        { palavra: "Barbeiro", dica: "Cabelo" },
        { palavra: "Maquiador", dica: "Rosto" },
        { palavra: "Modelo", dica: "Moda" },
        { palavra: "Cientista", dica: "Pesquisa" },
        { palavra: "Historiador", dica: "Passado" },
        { palavra: "Geógrafo", dica: "Terra" },
        { palavra: "Arqueólogo", dica: "Fóssil" },
        { palavra: "Biólogo", dica: "Vida" },
        { palavra: "Nutricionista", dica: "Alimento" },
        { palavra: "Personal Trainer", dica: "Treino" },
        { palavra: "Agrônomo", dica: "Terra" },
        { palavra: "Político", dica: "Voto" },
        { palavra: "Juiz", dica: "Lei" },
        { palavra: "Escritor", dica: "Texto" },
        { palavra: "Designer Gráfico", dica: "Arte" },
        { palavra: "Contador", dica: "Cálculo" },
        { palavra: "Secretária", dica: "Agenda" },
        { palavra: "Vendedor", dica: "Loja" }
    ],
    // ADICIONE ESTA NOVA CATEGORIA AQUI:
    lugares: [
        { palavra: "Pet Shop", dica: "Animais" },
        { palavra: "Sorveteria", dica: "Gelado" },
        { palavra: "Parque de Diversões", dica: "Brinquedo" },
        { palavra: "Cinema", dica: "Filme" },
        { palavra: "Supermercado", dica: "Compras" },
        { palavra: "Shopping", dica: "Lojas" },
        { palavra: "Praia", dica: "Areia" },
        { palavra: "Escola", dica: "Estudo" },
        { palavra: "Hospital", dica: "Saúde" },
        { palavra: "Restaurante", dica: "Comida" },
        { palavra: "Academia", dica: "Treino" },
        { palavra: "Aeroporto", dica: "Avião" },
        { palavra: "Rodoviária", dica: "Ônibus" },
        { palavra: "Hotel", dica: "Quarto" },
        { palavra: "Biblioteca", dica: "Livros" },
        { palavra: "Museu", dica: "Arte" },
        { palavra: "Igreja", dica: "Fé" },
        { palavra: "Farmácia", dica: "Remédio" },
        { palavra: "Banco", dica: "Dinheiro" },
        { palavra: "Padaria", dica: "Pão" },
        { palavra: "Estádio", dica: "Futebol" },
        { palavra: "Zoológico", dica: "Bichos" },
        { palavra: "Posto de Gasolina", dica: "Combustível" },
        { palavra: "Teatro", dica: "Palco" },
        { palavra: "Cemitério", dica: "Túmulo" },
        { palavra: "Delegacia", dica: "Polícia" },
        { palavra: "Parque", dica: "Árvores" },
        { palavra: "Salão de Beleza", dica: "Cabelo" },
        { palavra: "Oficina Mecânica", dica: "Carro" },
        { palavra: "Circo", dica: "Palhaço" },
        { palavra: "Faculdade", dica: "Curso" },
        { palavra: "Clube", dica: "Piscina" },
        { palavra: "Laboratório", dica: "Exame" },
        { palavra: "Floricultura", dica: "Planta" },
        { palavra: "Barbearia", dica: "Barba" },
        { palavra: "Livraria", dica: "Leitura" },
        { palavra: "Feira", dica: "Barraca" },
        { palavra: "Açougue", dica: "Carne" },
        { palavra: "Peixaria", dica: "Peixe" },
        { palavra: "Casamento / Igreja", dica: "Noiva" },
        { palavra: "Horto Florestal", dica: "Natureza" },
        { palavra: "Cassino", dica: "Jogo" },
        { palavra: "Museu de Cera", dica: "Estátua" },
        { palavra: "Aquário Municipal", dica: "Peixes" },
        { palavra: "Planetário", dica: "Estrelas" },
        { palavra: "Lan House", dica: "Computador" },
        { palavra: "Camping", dica: "Barraca" },
        { palavra: "Estação de Trem", dica: "Trilho" },
        { palavra: "Frigorífico", dica: "Frio" },
        { palavra: "Cartório", dica: "Papel" },
        { palavra: "Prefeitura", dica: "Prefeito" },
        { palavra: "Quitanda", dica: "Fruta" }
    ],
    animais: [
        { palavra: "Leão", dica: "Juba" },
        { palavra: "Tigre", dica: "Listras" },
        { palavra: "Elefante", dica: "Tromba" },
        { palavra: "Girafa", dica: "Pescoço" },
        { palavra: "Zebra", dica: "Listras" },
        { palavra: "Cachorro", dica: "Latido" },
        { palavra: "Gato", dica: "Miau" },
        { palavra: "Cavalo", dica: "Casco" },
        { palavra: "Vaca", dica: "Leite" },
        { palavra: "Galinha", dica: "Ovo" },
        { palavra: "Pato", dica: "Pena" },
        { palavra: "Águia", dica: "Voo" },
        { palavra: "Tubarão", dica: "Dente" },
        { palavra: "Baleia", dica: "Oceano" },
        { palavra: "Golfinho", dica: "Salto" },
        { palavra: "Jacaré", dica: "Pântano" },
        { palavra: "Cobra", dica: "Veneno" },
        { palavra: "Sapo", dica: "Salto" },
        { palavra: "Tartaruga", dica: "Casco" },
        { palavra: "Macaco", dica: "Banana" },
        { palavra: "Urso", dica: "Mel" },
        { palavra: "Lobo", dica: "Uivo" },
        { palavra: "Raposa", dica: "Cauda" },
        { palavra: "Coelho", dica: "Cenoura" },
        { palavra: "Canguru", dica: "Bolsa" },
        { palavra: "Pinguim", dica: "Gelo" },
        { palavra: "Urso Polar", dica: "Neve" },
        { palavra: "Panda", dica: "Bambu" },
        { palavra: "Hipopótamo", dica: "Rio" },
        { palavra: "Rinoceronte", dica: "Chifre" },
        { palavra: "Morcego", dica: "Caverna" },
        { palavra: "Rato", dica: "Queijo" },
        { palavra: "Esquilo", dica: "Noz" },
        { palavra: "Castor", dica: "Dique" },
        { palavra: "Camelo", dica: "Deserto" },
        { palavra: "Flamingo", dica: "Rosa" },
        { palavra: "Pavão", dica: "Penas" },
        { palavra: "Coruja", dica: "Noite" },
        { palavra: "Papagaio", dica: "Fala" },
        { palavra: "Beija-flor", dica: "Flor" },
        { palavra: "Formiga", dica: "Doce" },
        { palavra: "Abelha", dica: "Mel" },
        { palavra: "Borboleta", dica: "Asa" },
        { palavra: "Aranha", dica: "Teia" },
        { palavra: "Escorpião", dica: "Ferroada" },
        { palavra: "Polvo", dica: "Tentáculo" },
        { palavra: "Caranguejo", dica: "Praia" },
        { palavra: "Água-viva", dica: "Queimadura" },
        { palavra: "Ovelha", dica: "Lã" },
        { palavra: "Porco", dica: "Lama" },
        { palavra: "Bode", dica: "Chifre" },
        { palavra: "Peru", dica: "Natal" }
    ]
};

const nomesExibicaoCategorias = {
    comida: "Comida",
    famosos: "Famosos",
    objetos: "Objetos do Cotidiano",
    profissao: "Profissão",
    lugares: "Lugares",
    animais: "Animais" // Adicionado aqui
};