const bancoPalavras = {
    comida: [
        { palavra: "Pizza", dica: "Fatia" },
        { palavra: "Hambúrguer", dica: "Sessão" },
        { palavra: "Sushi", dica: "Esteira" },
        { palavra: "Chocolate", dica: "Barra" },
        { palavra: "Arroz", dica: "Vapor" },
        { palavra: "Sorvete", dica: "Casquinha" },
        { palavra: "Melancia", dica: "Fatia" },
        { palavra: "Pastel", dica: "Feira" },
        { palavra: "Coxinha", dica: "Bico" },
        { palavra: "Pipoca", dica: "Balde" },
        { palavra: "Pão", dica: "Massa" },
        { palavra: "Churrasco", dica: "Fumaça" },
        { palavra: "Açaí", dica: "Tigela" },
        { palavra: "Bolo", dica: "Festa" },
        { palavra: "Queijo", dica: "Furo" },
        { palavra: "Lasanha", dica: "Camadas" },
        { palavra: "Feijoada", dica: "Orelha" },
        { palavra: "Batata Frita", dica: "Palito" },
        { palavra: "Macarronada", dica: "Fio" },
        { palavra: "Estrogonofe", dica: "Palha" },
        { palavra: "Panqueca", dica: "Disco" },
        { palavra: "Tapioca", dica: "Goma" },
        { palavra: "Brigadeiro", dica: "Panela" },
        { palavra: "Pudim", dica: "Furo" },
        { palavra: "Gelatina", dica: "Forma" },
        { palavra: "Salada", dica: "Tempero" },
        { palavra: "Sopa", dica: "Concha" },
        { palavra: "Omelete", dica: "Dobra" },
        { palavra: "Sanduíche", dica: "Camadas" },
        { palavra: "Waffle", dica: "Grade" },
        { palavra: "Donut", dica: "Rosca" },
        { palavra: "Croissant", dica: "Lua" },
        { palavra: "Guacamole", dica: "Pasta" },
        { palavra: "Yakisoba", dica: "Tigela" },
        { palavra: "Paella", dica: "Tacho" },
        { palavra: "Biscoito", dica: "Pacote" },
        { palavra: "Torrada", dica: "Manteiga" },
        { palavra: "Panetone", dica: "Caixa" },
        { palavra: "Pão de Queijo", dica: "Cesta" },
        { palavra: "Farofa", dica: "Prato" },
        { palavra: "Empada", dica: "Forminha" },
        { palavra: "Quibe", dica: "Folha" },
        { palavra: "Esfiha", dica: "Triângulo" },
        { palavra: "Churros", dica: "Tubo" },
        { palavra: "Crepe", dica: "Rolo" },
        { palavra: "Iogurte", dica: "Pote" },
        { palavra: "Fondue", dica: "Espeto" },
        { palavra: "Risoto", dica: "Panela" },
        { palavra: "Nugget", dica: "Caixa" },
        { palavra: "Cuscuz", dica: "Milho" },
        { palavra: "Beijinho", dica: "Cravo" },
        { palavra: "Torta de Limão", dica: "Fatia" },
        // --- EXPANSÃO ATÉ 60 ITENS ---
        { palavra: "Misto Quente", dica: "Prensa" },
        { palavra: "Miojo", dica: "Pacote" },
        { palavra: "Bolo de Cenoura", dica: "Cobertura" },
        { palavra: "Paçoca", dica: "Rolha" },
        { palavra: "Pamonha", dica: "Palha" },
        { palavra: "Sonho", dica: "Creme" },
        { palavra: "Torresmo", dica: "Pele" },
        { palavra: "Polenta", dica: "Fubá" }
    ],
    famosos: [
        { palavra: "Neymar", dica: "Moicano" },
        { palavra: "Anitta", dica: "Poderosa" },
        { palavra: "Silvio Santos", dica: "Microfone" },
        { palavra: "Faustão", dica: "Domingo" },
        { palavra: "Cristiano Ronaldo", dica: "Robô" },
        { palavra: "Beyoncé", dica: "Coroa" },
        { palavra: "Michael Jackson", dica: "Luva" },
        { palavra: "Lionel Messi", dica: "Canhota" },
        { palavra: "Lady Gaga", dica: "Carne" },
        { palavra: "Keanu Reeves", dica: "Pílula" },
        { palavra: "Leonardo DiCaprio", dica: "Navio" },
        { palavra: "Ayrton Senna", dica: "Capacete" },
        { palavra: "Taylor Swift", dica: "Pulseira" },
        { palavra: "Will Smith", dica: "Tapa" },
        { palavra: "Angelina Jolie", dica: "Túmulo" },
        { palavra: "Brad Pitt", dica: "Clube" },
        { palavra: "Tom Cruise", dica: "Paraquedas" },
        { palavra: "Rihanna", dica: "Guarda-chuva" },
        { palavra: "Eminem", dica: "Capuz" },
        { palavra: "Shakira", dica: "Quadril" },
        { palavra: "Ivete Sangalo", dica: "Poeira" },
        { palavra: "Luan Santana", dica: "Meteoro" },
        { palavra: "Gusttavo Lima", dica: "Embaixador" },
        { palavra: "Xuxa", dica: "Nave" },
        { palavra: "Pelé", dica: "Rei" },
        { palavra: "Maradona", dica: "Mão" },
        { palavra: "Elon Musk", dica: "Foguete" },
        { palavra: "Bill Gates", dica: "Janela" },
        { palavra: "Steve Jobs", dica: "Maçã" },
        { palavra: "Albert Einstein", dica: "Língua" },
        { palavra: "William Shakespeare", dica: "Caveira" },
        { palavra: "Machado de Assis", dica: "Literatura" },
        { palavra: "Billie Eilish", dica: "Verde" },
        { palavra: "Gisele Bündchen", dica: "Passarela" },
        { palavra: "Whindersson Nunes", dica: "Palco" },
        { palavra: "Casimiro", dica: "Reação" },
        { palavra: "Robert Downey Jr", dica: "Armadura" },
        { palavra: "Dwayne Johnson", dica: "Pedra" },
        { palavra: "Vini Jr", dica: "Baila" },
        { palavra: "Justin Bieber", dica: "Franja" },
        { palavra: "Ronaldo Fenômeno", dica: "Fenômeno" },
        { palavra: "Freddie Mercury", dica: "Bigode" },
        { palavra: "Johnny Depp", dica: "Bússola" },
        { palavra: "Morgan Freeman", dica: "Voz" },
        { palavra: "Jackie Chan", dica: "Cadeira" },
        { palavra: "Marta", dica: "Chuteira" },
        { palavra: "Thiaguinho", dica: "Tardezinha" },
        { palavra: "Alok", dica: "Laser" },
        { palavra: "Ludmilla", dica: "Pagode" },
        { palavra: "Ariana Grande", dica: "Anel" },
        { palavra: "Ronaldinho Gaúcho", dica: "Bruxo" },
        { palavra: "Galvão Bueno", dica: "Tetra" },
        { palavra: "Marília Mendonça", dica: "Sofrência" },
        { palavra: "Roberto Carlos", dica: "Ano Novo" },
        { palavra: "Ana Maria Braga", dica: "Louro" },
        { palavra: "Felipe Neto", dica: "Coruja" },
        { palavra: "Mano Brown", dica: "Racionais" },
        { palavra: "Wagner Moura", dica: "Tropa" },
        { palavra: "Chaves", dica: "Barril" },
        { palavra: "Luccas Neto", dica: "Banheira" }
    ],
    objetos: [
        { palavra: "Celular", dica: "Notificação" },
        { palavra: "Chave", dica: "Segredo" },
        { palavra: "Relógio", dica: "Ponteiro" },
        { palavra: "Caneta", dica: "Tinta" },
        { palavra: "Cadeira", dica: "Encosto" },
        { palavra: "Garrafa", dica: "Gargalo" },
        { palavra: "Óculos", dica: "Grau" },
        { palavra: "Mochila", dica: "Zíper" },
        { palavra: "Caderno", dica: "Espiral" },
        { palavra: "Sapato", dica: "Cadarço" },
        { palavra: "Guarda-chuva", dica: "Haste" },
        { palavra: "Controle Remoto", dica: "Pilha" },
        { palavra: "Carteira", dica: "Bolso" },
        { palavra: "Espelho", dica: "Reflexo" },
        { palavra: "Fone de Ouvido", dica: "Graves" },
        { palavra: "Televisão", dica: "Polegadas" },
        { palavra: "Computador", dica: "Placa" },
        { palavra: "Livro", dica: "Capítulo" },
        { palavra: "Luminária", dica: "Cúpula" },
        { palavra: "Almofada", dica: "Estofado" },
        { palavra: "Toalha", dica: "Pano" },
        { palavra: "Escova de Dentes", dica: "Cerdas" },
        { palavra: "Pente", dica: "Dentes" },
        { palavra: "Sabonete", dica: "Espuma" },
        { palavra: "Tesoura", dica: "Lâmina" },
        { palavra: "Martelo", dica: "Cabo" },
        { palavra: "Faca", dica: "Fio" },
        { palavra: "Garfo", dica: "Pontas" },
        { palavra: "Prato", dica: "Borda" },
        { palavra: "Copo", dica: "Vidro" },
        { palavra: "Panela", dica: "Tampa" },
        { palavra: "Vassoura", dica: "Cerdas" },
        { palavra: "Balde", dica: "Alça" },
        { palavra: "Cama", dica: "Colchão" },
        { palavra: "Travesseiro", dica: "Fronha" },
        { palavra: "Sofá", dica: "Retrátil" },
        { palavra: "Mesa", dica: "Tampo" },
        { palavra: "Tapete", dica: "Piso" },
        { palavra: "Cortina", dica: "Trilho" },
        { palavra: "Ventilador", dica: "Hélice" },
        { palavra: "Geladeira", dica: "Gelo" },
        { palavra: "Micro-ondas", dica: "Timer" },
        { palavra: "Ferro de Passar", dica: "Vapor" },
        { palavra: "Maleta", dica: "Fecho" },
        { palavra: "Grampeador", dica: "Grampo" },
        { palavra: "Calculadora", dica: "Teclas" },
        { palavra: "Carregador", dica: "Tomada" },
        { palavra: "Isqueiro", dica: "Faísca" },
        { palavra: "Cadeado", dica: "Tranca" },
        { palavra: "Anel", dica: "Aro" },
        { palavra: "Chave de Fenda", dica: "Pontas" },
        { palavra: "Lanterna", dica: "Foco" },
        { palavra: "Pano de Prato", dica: "Bordado" },
        { palavra: "Pregador de Roupa", dica: "Mola" },
        { palavra: "Cabide", dica: "Gancho" },
        { palavra: "Roteador", dica: "Sinal" },
        { palavra: "Perfume", dica: "Frasco" },
        { palavra: "Moeda", dica: "Troco" },
        { palavra: "Vela", dica: "Pavio" },
        { palavra: "Bateria", dica: "Carga" }
    ],
    profissao: [
        { palavra: "Médico", dica: "Saúde" },
        { palavra: "Professor", dica: "Ensino" },
        { palavra: "Policial", dica: "Lei" },
        { palavra: "Bombeiro", dica: "Fogo" },
        { palavra: "Advogado", dica: "Defesa" },
        { palavra: "Engenheiro", dica: "Cálculo" },
        { palavra: "Chef de Cozinha", dica: "Culinária" },
        { palavra: "Dentista", dica: "Dente" },
        { palavra: "Astronauta", dica: "Espaço" },
        { palavra: "Veterinário", dica: "Animal" },
        { palavra: "Pintor", dica: "Tinta" },
        { palavra: "Programador", dica: "Código" },
        { palavra: "Fotógrafo", dica: "Câmera" },
        { palavra: "Músico", dica: "Som" },
        { palavra: "Motorista", dica: "Carro" },
        { palavra: "Arquiteto", dica: "Desenho" },
        { palavra: "Jornalista", dica: "Notícia" },
        { palavra: "Enfermeiro", dica: "Cuidado" },
        { palavra: "Psicólogo", dica: "Terapia" },
        { palavra: "Farmacêutico", dica: "Remédio" },
        { palavra: "Ator", dica: "Teatro" },
        { palavra: "Dançarino", dica: "Dança" },
        { palavra: "Piloto de Avião", dica: "Voo" },
        { palavra: "Comissário de Bordo", dica: "Avião" },
        { palavra: "Marinheiro", dica: "Navio" },
        { palavra: "Militar", dica: "Farda" },
        { palavra: "Eletricista", dica: "Fio" },
        { palavra: "Encanador", dica: "Cano" },
        { palavra: "Pedreiro", dica: "Obra" },
        { palavra: "Carpinteiro", dica: "Madeira" },
        { palavra: "Mecânico", dica: "Motor" },
        { palavra: "Carteiro", dica: "Carta" },
        { palavra: "Gari", dica: "Rua" },
        { palavra: "Barbeiro", dica: "Cabelo" },
        { palavra: "Maquiador", dica: "Rosto" },
        { palavra: "Modelo", dica: "Moda" },
        { palavra: "Cientista", dica: "Pesquisa" },
        { palavra: "Historiador", dica: "Passado" },
        { palavra: "Geógrafo", dica: "Terra" },
        { palavra: "Arqueólogo", dica: "Fóssil" },
        { palavra: "Biólogo", dica: "Vida" },
        { palavra: "Nutricionista", dica: "Alimento" },
        { palavra: "Personal Trainer", dica: "Treino" },
        { palavra: "Agrônomo", dica: "Campo" },
        { palavra: "Político", dica: "Voto" },
        { palavra: "Juiz", dica: "Tribunal" },
        { palavra: "Escritor", dica: "Texto" },
        { palavra: "Designer Gráfico", dica: "Arte" },
        { palavra: "Contador", dica: "Imposto" },
        { palavra: "Secretária", dica: "Agenda" },
        { palavra: "Vendedor", dica: "Loja" },
        // --- ADICIONADOS PARA COMPLETAR 60 ---
        { palavra: "Padeiro", dica: "Pão" },
        { palavra: "Garçom", dica: "Mesa" },
        { palavra: "Taxista", dica: "Corrida" },
        { palavra: "Costureira", dica: "Agulha" },
        { palavra: "Dublador", dica: "Voz" },
        { palavra: "Segurança", dica: "Vigilância" },
        { palavra: "Fisioterapeuta", dica: "Movimento" },
        { palavra: "Cozinheiro", dica: "Panela" },
        { palavra: "Detetive", dica: "Pista" }
    ],
    lugares: [
        { palavra: "Pet Shop", dica: "Animais" },
        { palavra: "Sorveteria", dica: "Gelado" },
        { palavra: "Parque de Diversões", dica: "Brinquedo" },
        { palavra: "Cinema", dica: "Filme" },
        { palavra: "Supermercado", dica: "Compras" },
        { palavra: "Shopping", dica: "Lojas" },
        { palavra: "Praia", dica: "Areia" },
        { palavra: "Escola", dica: "Estudo" },
        { palavra: "Hospital", dica: "Saúde" },
        { palavra: "Restaurante", dica: "Comida" },
        { palavra: "Academia", dica: "Treino" },
        { palavra: "Aeroporto", dica: "Avião" },
        { palavra: "Rodoviária", dica: "Ônibus" },
        { palavra: "Hotel", dica: "Quarto" },
        { palavra: "Biblioteca", dica: "Livros" },
        { palavra: "Museu", dica: "Arte" },
        { palavra: "Igreja", dica: "Fé" },
        { palavra: "Farmácia", dica: "Remédio" },
        { palavra: "Banco", dica: "Dinheiro" },
        { palavra: "Padaria", dica: "Pão" },
        { palavra: "Estádio", dica: "Futebol" },
        { palavra: "Zoológico", dica: "Bichos" },
        { palavra: "Posto de Gasolina", dica: "Combustível" },
        { palavra: "Teatro", dica: "Palco" },
        { palavra: "Cemitério", dica: "Túmulo" },
        { palavra: "Delegacia", dica: "Polícia" },
        { palavra: "Parque", dica: "Árvores" },
        { palavra: "Salão de Beleza", dica: "Cabelo" },
        { palavra: "Oficina Mecânica", dica: "Carro" },
        { palavra: "Circo", dica: "Palhaço" },
        { palavra: "Faculdade", dica: "Curso" },
        { palavra: "Clube", dica: "Piscina" },
        { palavra: "Laboratório", dica: "Exame" },
        { palavra: "Floricultura", dica: "Planta" },
        { palavra: "Barbearia", dica: "Barba" },
        { palavra: "Livraria", dica: "Leitura" },
        { palavra: "Feira", dica: "Barraca" },
        { palavra: "Açougue", dica: "Carne" },
        { palavra: "Peixaria", dica: "Peixe" },
        { palavra: "Cassino", dica: "Jogo" },
        { palavra: "Planetário", dica: "Estrelas" },
        { palavra: "Lan House", dica: "Computador" },
        { palavra: "Camping", dica: "Barraca" },
        { palavra: "Estação de Trem", dica: "Trilho" },
        { palavra: "Cartório", dica: "Documento" },
        { palavra: "Prefeitura", dica: "Cidade" },
        { palavra: "Pizzaria", dica: "Forno" },
        { palavra: "Lanchonete", dica: "Lanche" },
        { palavra: "Praça", dica: "Banco" },
        { palavra: "Lava-Rápido", dica: "Carro" },
        { palavra: "Maternidade", dica: "Bebê" },
        { palavra: "Quadra", dica: "Esporte" },
        { palavra: "Pousada", dica: "Viagem" },
        { palavra: "Tribunal", dica: "Juiz" },
        { palavra: "Balada", dica: "Festa" },
        { palavra: "Estacionamento", dica: "Vaga" },
        { palavra: "Rodízio", dica: "Comida" },
        { palavra: "Lanchonete", dica: "Salgado" },
        { palavra: "Churrascaria", dica: "Espeto" },
        { palavra: "Pizzaria", dica: "Massa" }
    ],
    animais: [
        { palavra: "Leão", dica: "Juba" },
        { palavra: "Tigre", dica: "Listras" },
        { palavra: "Elefante", dica: "Amendoim" },
        { palavra: "Girafa", dica: "Pescoço" },
        { palavra: "Zebra", dica: "Faixa" },
        { palavra: "Cachorro", dica: "Coleira" },
        { palavra: "Gato", dica: "Bigode" },
        { palavra: "Cavalo", dica: "Ferradura" },
        { palavra: "Vaca", dica: "Mastigar" },
        { palavra: "Galinha", dica: "Milho" },
        { palavra: "Pato", dica: "Lagoa" },
        { palavra: "Águia", dica: "Garra" },
        { palavra: "Tubarão", dica: "Barbatana" },
        { palavra: "Baleia", dica: "Sopro" },
        { palavra: "Golfinho", dica: "Salto" },
        { palavra: "Jacaré", dica: "Lago" },
        { palavra: "Cobra", dica: "Veneno" },
        { palavra: "Sapo", dica: "Brejo" },
        { palavra: "Tartaruga", dica: "Casco" },
        { palavra: "Macaco", dica: "Galho" },
        { palavra: "Urso", dica: "Mel" },
        { palavra: "Lobo", dica: "Uivo" },
        { palavra: "Raposa", dica: "Cauda" },
        { palavra: "Coelho", dica: "Cenoura" },
        { palavra: "Canguru", dica: "Bolsa" },
        { palavra: "Pinguim", dica: "Gelo" },
        { palavra: "Urso Polar", dica: "Neve" },
        { palavra: "Panda", dica: "Bambu" },
        { palavra: "Hipopótamo", dica: "Barro" },
        { palavra: "Rinoceronte", dica: "Chifre" },
        { palavra: "Morcego", dica: "Caverna" },
        { palavra: "Rato", dica: "Queijo" },
        { palavra: "Esquilo", dica: "Noz" },
        { palavra: "Castor", dica: "Dique" },
        { palavra: "Camelo", dica: "Corcova" },
        { palavra: "Flamingo", dica: "Perna" },
        { palavra: "Pavão", dica: "Leque" },
        { palavra: "Coruja", dica: "Noite" },
        { palavra: "Papagaio", dica: "Fala" },
        { palavra: "Beija-flor", dica: "Jardim" },
        { palavra: "Formiga", dica: "Açúcar" },
        { palavra: "Abelha", dica: "Colmeia" },
        { palavra: "Borboleta", dica: "Casulo" },
        { palavra: "Aranha", dica: "Teia" },
        { palavra: "Escorpião", dica: "Ferroada" },
        { palavra: "Polvo", dica: "Tinta" },
        { palavra: "Caranguejo", dica: "Praia" },
        { palavra: "Água-viva", dica: "Queimadura" },
        { palavra: "Ovelha", dica: "Lã" },
        { palavra: "Porco", dica: "Lama" },
        { palavra: "Bode", dica: "Chifre" },
        { palavra: "Peru", dica: "Natal" },
        { palavra: "Bicho-Preguiça", dica: "Lento" },
        { palavra: "Capivara", dica: "Carrapato" },
        { palavra: "Tatu", dica: "Toca" },
        { palavra: "Tamanduá", dica: "Cupim" },
        { palavra: "Camaleão", dica: "Cor" },
        { palavra: "Piranha", dica: "Mordida" },
        { palavra: "Vagalume", dica: "Luz" },
        { palavra: "Joaninha", dica: "Pintas" }
    ],
};

const nomesExibicaoCategorias = {
    comida: "Comida",
    famosos: "Famosos",
    objetos: "Objetos",
    profissao: "Profissão",
    lugares: "Lugares",
    animais: "Animais"
};