const bancoPalavras = {
    comida: [
        { palavra: "Pizza", dica: "Fatia" },
        { palavra: "Hambúrguer", dica: "Carne" },
        { palavra: "Sushi", dica: "Peixe" },
        { palavra: "Batata Frita", dica: "Sal" },
        { palavra: "Chocolate", dica: "Cacau" },
        { palavra: "Sorvete", dica: "Gelado" },
        { palavra: "Brigadeiro", dica: "Granulado" },
        { palavra: "Pão de Queijo", dica: "Forno" },
        { palavra: "Pastel", dica: "Frito" },
        { palavra: "Pipoca", dica: "Milho" },
        { palavra: "Cachorro-quente", dica: "Salsicha" },
        { palavra: "Feijoada", dica: "Feijão" },
        { palavra: "Estrogonofe", dica: "Creme" },
        { palavra: "Lasanha", dica: "Massa" },
        { palavra: "Pudim", dica: "Calda" },
        { palavra: "Misto Quente", dica: "Queijo" },
        { palavra: "Bolo de Cenoura", dica: "Cobertura" },
        { palavra: "Coxinha", dica: "Frango" },
        { palavra: "Miojo", dica: "Macarrão" },
        { palavra: "Açaí", dica: "Roxo" },
        { palavra: "Churrasco", dica: "Carne" },
        { palavra: "Paçoca", dica: "Amendoim" },
        { palavra: "Tapioca", dica: "Mandioca" },
        { palavra: "Pamonha", dica: "Milho" },
        { palavra: "Pão francês", dica: "Padaria" },
        { palavra: "Gelatina", dica: "Doce" },
        { palavra: "Sonho", dica: "Creme" },
        { palavra: "Donut", dica: "Açúcar" },
        { palavra: "Churros", dica: "Frito" },
        { palavra: "Omelete", dica: "Ovo" },
        { palavra: "Salada", dica: "Alface" },
        { palavra: "Sopa", dica: "Quente" },
        { palavra: "Milho Cozido", dica: "Espiga" },
        { palavra: "Melancia", dica: "Fruta" },
        { palavra: "Banana", dica: "Casca" },
        { palavra: "Morango", dica: "Fruta" },
        { palavra: "Biscoito Recheado", dica: "Doce" },
        { palavra: "Torrada", dica: "Pão" },
        { palavra: "Guaraná", dica: "Bebida" },
        { palavra: "Café", dica: "Preto" },
        { palavra: "Suco de Laranja", dica: "Fruta" },
        { palavra: "Yakult", dica: "Leite" },
        { palavra: "Waffle", dica: "Massa" },
        { palavra: "Esfiha", dica: "Massa" },
        { palavra: "Nugget", dica: "Frango" },
        { palavra: "Polenta Frita", dica: "Fubá" },
        { palavra: "Torresmo", dica: "Porco" },
        { palavra: "Torta de Limão", dica: "Azedo" },
        { palavra: "Panqueca", dica: "Massa" },
        { palavra: "Mousse de Chocolate", dica: "Creme" },
        { palavra: "Arroz e Feijão", dica: "Prato" },
        { palavra: "Panetone", dica: "Natal" },
        // --- EXPANSÃO ATÉ 100 PALAVRAS ---
        { palavra: "Ketchup", dica: "Molho" },
        { palavra: "Maionese", dica: "Molho" },
        { palavra: "Mostarda", dica: "Molho" },
        { palavra: "Macarrão instantâneo", dica: "Massa" },
        { palavra: "Bife Acebolado", dica: "Carne" },
        { palavra: "Purê de Batata", dica: "Creme" },
        { palavra: "Salpicão", dica: "Frango" },
        { palavra: "Farofa", dica: "Fubá" },
        { palavra: "Empadinha", dica: "Forno" },
        { palavra: "Quibe", dica: "Frito" },
        { palavra: "Croquete", dica: "Frito" },
        { palavra: "Pão de Mel", dica: "Doce" },
        { palavra: "Beijinho", dica: "Coco" },
        { palavra: "Quindim", dica: "Ovo" },
        { palavra: "Petit Gateau", dica: "Gelado" },
        { palavra: "Brownie", dica: "Chocolate" },
        { palavra: "Cookies", dica: "Gotas" },
        { palavra: "Bolo de Chocolate", dica: "Cacau" },
        { palavra: "Almôndega", dica: "Carne" },
        { palavra: "Yakisoba", dica: "Macarrão" },
        { palavra: "Guacamole", dica: "Abacate" },
        { palavra: "Taco", dica: "Massa" },
        { palavra: "Nacho", dica: "Crocante" },
        { palavra: "Pipoca Doce", dica: "Açúcar" },
        { palavra: "Algodão Doce", dica: "Açúcar" },
        { palavra: "Rapadura", dica: "Dura" },
        { palavra: "Ovo Frito", dica: "Gema" },
        { palavra: "Batata Palha", dica: "Saco" },
        { palavra: "Caldo de Cana", dica: "Bebida" },
        { palavra: "Suco de Uva", dica: "Bebida" },
        { palavra: "Refrigerante de Cola", dica: "Gás" },
        { palavra: "Chocolate Branco", dica: "Barra" },
        { palavra: "Queijo Minas", dica: "Branco" },
        { palavra: "Doce de Leite", dica: "Colher" },
        { palavra: "Goiabada", dica: "Doce" },
        { palavra: "Mel", dica: "Abelha" },
        { palavra: "Gelado de Abacaxi", dica: "Geladeira" },
        { palavra: "Crepe", dica: "Massa" },
        { palavra: "Onion Rings", dica: "Frito" },
        { palavra: "Salsicha", dica: "Fervida" },
        { palavra: "Salame", dica: "Fatia" },
        { palavra: "Presunto", dica: "Fatia" },
        { palavra: "Bacon", dica: "Frito" },
        { palavra: "Mingau", dica: "Aveia" },
        { palavra: "Cereal", dica: "Leite" },
        { palavra: "Danone", dica: "Morango" },
        { palavra: "Uva Passa", dica: "Natal" },
        { palavra: "Milho Verde", dica: "Lata" },
        { palavra: "Ervilha", dica: "Verde" }
    ],
    famosos: [
        { palavra: "Neymar", dica: "Futebol" },
        { palavra: "Anitta", dica: "Música" },
        { palavra: "Silvio Santos", dica: "Televisão" },
        { palavra: "Faustão", dica: "Televisão" },
        { palavra: "Cristiano Ronaldo", dica: "Futebol" },
        { palavra: "Lionel Messi", dica: "Futebol" },
        { palavra: "Michael Jackson", dica: "Pop" },
        { palavra: "Beyoncé", dica: "Pop" },
        { palavra: "Lady Gaga", dica: "Pop" },
        { palavra: "Taylor Swift", dica: "Cantora" },
        { palavra: "Rihanna", dica: "Música" },
        { palavra: "Justin Bieber", dica: "Música" },
        { palavra: "Eminem", dica: "Rap" },
        { palavra: "Shakira", dica: "Cantora" },
        { palavra: "Ivete Sangalo", dica: "Axé" },
        { palavra: "Luan Santana", dica: "Sertanejo" },
        { palavra: "Gusttavo Lima", dica: "Sertanejo" },
        { palavra: "Zeca Pagodinho", dica: "Samba" },
        { palavra: "Ludmilla", dica: "Cantora" },
        { palavra: "Alok", dica: "Música" },
        { palavra: "Ariana Grande", dica: "Música" },
        { palavra: "Billie Eilish", dica: "Música" },
        { palavra: "Xuxa", dica: "Televisão" },
        { palavra: "Angélica", dica: "Televisão" },
        { palavra: "Pelé", dica: "Futebol" },
        { palavra: "Maradona", dica: "Futebol" },
        { palavra: "Marta", dica: "Futebol" },
        { palavra: "Ayrton Senna", dica: "Corrida" },
        { palavra: "Lewis Hamilton", dica: "Corrida" },
        { palavra: "Elon Musk", dica: "Foguete" },
        { palavra: "Bill Gates", dica: "Computador" },
        { palavra: "Steve Jobs", dica: "Celular" },
        { palavra: "Albert Einstein", dica: "Física" },
        { palavra: "Machado de Assis", dica: "Livro" },
        { palavra: "William Shakespeare", dica: "Teatro" },
        { palavra: "Whindersson Nunes", dica: "Comédia" },
        { palavra: "Casimiro", dica: "Internet" },
        { palavra: "Bruna Marquezine", dica: "Atriz" },
        { palavra: "Angelina Jolie", dica: "Cinema" },
        { palavra: "Brad Pitt", dica: "Ator" },
        { palavra: "Leonardo DiCaprio", dica: "Cinema" },
        { palavra: "Tom Cruise", dica: "Cinema" },
        { palavra: "Keanu Reeves", dica: "Cinema" },
        { palavra: "Will Smith", dica: "Ator" },
        { palavra: "Robert Downey Jr", dica: "Cinema" },
        { palavra: "Dwayne Johnson", dica: "Cinema" },
        { palavra: "Johnny Depp", dica: "Ator" },
        { palavra: "Morgan Freeman", dica: "Voz" },
        { palavra: "Jackie Chan", dica: "Luta" },
        { palavra: "Freddie Mercury", dica: "Rock" },
        { palavra: "Selena Gomez", dica: "Música" },
        { palavra: "Willian Bonner", dica: "Jornal" },
        // --- EXPANSÃO ATÉ 100 FAMOSOS ---
        { palavra: "Ronaldinho Gaúcho", dica: "Futebol" },
        { palavra: "Ronaldo Fenômeno", dica: "Futebol" },
        { palavra: "Galvão Bueno", dica: "Televisão" },
        { palavra: "Ana Maria Braga", dica: "Televisão" },
        { palavra: "Luciano Huck", dica: "Televisão" },
        { palavra: "Marcos Mion", dica: "Televisão" },
        { palavra: "Rodrigo Faro", dica: "Televisão" },
        { palavra: "Eliana", dica: "Televisão" },
        { palavra: "Fátima Bernardes", dica: "Televisão" },
        { palavra: "Pedro Bial", dica: "Televisão" },
        { palavra: "Tadeu Schmidt", dica: "Televisão" },
        { palavra: "Maísa", dica: "Atriz" },
        { palavra: "Larissa Manoela", dica: "Atriz" },
        { palavra: "Marina Ruy Barbosa", dica: "Atriz" },
        { palavra: "Selton Mello", dica: "Cinema" },
        { palavra: "Wagner Moura", dica: "Cinema" },
        { palavra: "Lázaro Ramos", dica: "Ator" },
        { palavra: "Juliana Paes", dica: "Atriz" },
        { palavra: "Fernanda Montenegro", dica: "Atriz" },
        { palavra: "Paulo Gustavo", dica: "Comédia" },
        { palavra: "Renato Aragão", dica: "Comédia" },
        { palavra: "Chico Anysio", dica: "Comédia" },
        { palavra: "Roberto Carlos", dica: "Música" },
        { palavra: "Jorge e Mateus", dica: "Sertanejo" },
        { palavra: "Marília Mendonça", dica: "Sertanejo" },
        { palavra: "Luísa Sonza", dica: "Pop" },
        { palavra: "Pabllo Vittar", dica: "Pop" },
        { palavra: "Jão", dica: "Música" },
        { palavra: "Seu Jorge", dica: "Música" },
        { palavra: "Djavan", dica: "Música" },
        { palavra: "Caetano Veloso", dica: "Música" },
        { palavra: "Gilberto Gil", dica: "Música" },
        { palavra: "Chorão", dica: "Rock" },
        { palavra: "Mano Brown", dica: "Rap" },
        { palavra: "Felipe Neto", dica: "Internet" },
        { palavra: "Virginia Fonseca", dica: "Internet" },
        { palavra: "Podpah", dica: "Internet" },
        { palavra: "Alana", dica: "Internet" },
        { palavra: "SBT", dica: "Televisão" },
        { palavra: "Rede Globo", dica: "Televisão" },
        { palavra: "Silvester Stallone", dica: "Cinema" },
        { palavra: "Arnold Schwarzenegger", dica: "Cinema" },
        { palavra: "Vin Diesel", dica: "Cinema" },
        { palavra: "Zendaya", dica: "Cinema" },
        { palavra: "Chris Hemsworth", dica: "Ator" },
        { palavra: "Tom Holland", dica: "Cinema" },
        { palavra: "Katy Perry", dica: "Pop" },
        { palavra: "Bruno Mars", dica: "Pop" }
    ],
    objetos: [
        { palavra: "Celular", dica: "Tela" },
        { palavra: "Notebook", dica: "Teclado" },
        { palavra: "Televisão", dica: "Controle" },
        { palavra: "Fone de Ouvido", dica: "Som" },
        { palavra: "Relógio", dica: "Hora" },
        { palavra: "Chave", dica: "Fechadura" },
        { palavra: "Carteira", dica: "Dinheiro" },
        { palavra: "Óculos", dica: "Lente" },
        { palavra: "Caneta", dica: "Tinta" },
        { palavra: "Lápis", dica: "Grafite" },
        { palavra: "Caderno", dica: "Papel" },
        { palavra: "Mochila", dica: "Zíper" },
        { palavra: "Guarda-chuva", dica: "Chuva" },
        { palavra: "Garrafa de Água", dica: "Sede" },
        { palavra: "Copo", dica: "Vidro" },
        { palavra: "Prato", dica: "Comida" },
        { palavra: "Garfo", dica: "Metal" },
        { palavra: "Faca", dica: "Corte" },
        { palavra: "Colher", dica: "Sopa" },
        { palavra: "Panela", dica: "Fogão" },
        { palavra: "Cadeira", dica: "Assento" },
        { palavra: "Mesa", dica: "Madeira" },
        { palavra: "Cama", dica: "Travesseiro" },
        { palavra: "Espelho", dica: "Reflexo" },
        { palavra: "Toalha", dica: "Banho" },
        { palavra: "Escova de Dentes", dica: "Pia" },
        { palavra: "Sabonete", dica: "Espuma" },
        { palavra: "Secador de Cabelo", dica: "Vento" },
        { palavra: "Almofada", dica: "Sofá" },
        { palavra: "Tapete", dica: "Chão" },
        { palavra: "Cortina", dica: "Janela" },
        { palavra: "Lâmpada", dica: "Luz" },
        { palavra: "Ventilador", dica: "Vento" },
        { palavra: "Geladeira", dica: "Frio" },
        { palavra: "Micro-ondas", dica: "Quente" },
        { palavra: "Vassoura", dica: "Limpeza" },
        { palavra: "Balde", dica: "Água" },
        { palavra: "Martelo", dica: "Prego" },
        { palavra: "Chave de Fenda", dica: "Parafuso" },
        { palavra: "Tesoura", dica: "Corte" },
        { palavra: "Fita Isolante", dica: "Gruda" },
        { palavra: "Cadeado", dica: "Tranca" },
        { palavra: "Calculadora", dica: "Conta" },
        { palavra: "Livro", dica: "Páginas" },
        { palavra: "Bateria", dica: "Carga" },
        { palavra: "Lanterna", dica: "Luz" },
        { palavra: "Isqueiro", dica: "Fogo" },
        { palavra: "Vela", dica: "Cera" },
        { palavra: "Controle Remoto", dica: "Pilhas" },
        { palavra: "Travesseiro", dica: "Sono" },
        { palavra: "Moeda", dica: "Metal" },
        { palavra: "Sacola", dica: "Plástico" },
        // --- EXPANSÃO ATÉ 100 OBJETOS ---
        { palavra: "Grampeador", dica: "Grampo" },
        { palavra: "Borracha", dica: "Apaga" },
        { palavra: "Régua", dica: "Medida" },
        { palavra: "Apontador", dica: "Grafite" },
        { palavra: "Quadro Branco", dica: "Parede" },
        { palavra: "Pendrive", dica: "Arquivo" },
        { palavra: "Mouse", dica: "Clique" },
        { palavra: "Filtro de Linha", dica: "Tomada" },
        { palavra: "Roteador", dica: "Internet" },
        { palavra: "Tomada", dica: "Energia" },
        { palavra: "Fio Elétrico", dica: "Metal" },
        { palavra: "Prego", dica: "Metal" },
        { palavra: "Parafuso", dica: "Metal" },
        { palavra: "Alicate", dica: "Metal" },
        { palavra: "Trena", dica: "Medida" },
        { palavra: "Estilete", dica: "Corte" },
        { palavra: "Pano de Prato", dica: "Cozinha" },
        { palavra: "Esponja de Pia", dica: "Espuma" },
        { palavra: "Rodo", dica: "Limpeza" },
        { palavra: "Pá de Lixo", dica: "Limpeza" },
        { palavra: "Pregador de Roupa", dica: "Varal" },
        { palavra: "Cabide", dica: "Armário" },
        { palavra: "Ferro de Passar", dica: "Quente" },
        { palavra: "Perfume", dica: "Cheiro" },
        { palavra: "Desodorante", dica: "Cheiro" },
        { palavra: "Xampu", dica: "Banho" },
        { palavra: "Pente", dica: "Cabelo" },
        { palavra: "Cortador de Unha", dica: "Metal" },
        { palavra: "Papel Higiênico", dica: "Banheiro" },
        { palavra: "Lixeira", dica: "Tampa" },
        { palavra: "Xícara", dica: "Alça" },
        { palavra: "Abridor de Garrafa", dica: "Metal" },
        { palavra: "Abridor de Lata", dica: "Metal" },
        { palavra: "Saca-rolhas", dica: "Vinho" },
        { palavra: "Forma de Gelo", dica: "Geladeira" },
        { palavra: "Isopor", dica: "Frio" },
        { palavra: "Quadro", dica: "Moldura" },
        { palavra: "Relógio de Parede", dica: "Hora" },
        { palavra: "Vaso de Planta", dica: "Terra" },
        { palavra: "Cinzeiro", dica: "Mesa" },
        { palavra: "Fósforo", dica: "Fogo" },
        { palavra: "Termômetro", dica: "Febre" },
        { palavra: "Balança", dica: "Peso" },
        { palavra: "Chupeta", dica: "Bebê" },
        { palavra: "Mamadeira", dica: "Bebê" },
        { palavra: "Brinquedo", dica: "Criança" },
        { palavra: "Guardanapo", dica: "Papel" },
        { palavra: "Bota", dica: "Pé" }
    ],
    profissao: [
        { palavra: "Médico", dica: "Hospital" },
        { palavra: "Enfermeiro", dica: "Injeção" },
        { palavra: "Dentista", dica: "Dente" },
        { palavra: "Veterinário", dica: "Animal" },
        { palavra: "Professor", dica: "Aula" },
        { palavra: "Policial", dica: "Farda" },
        { palavra: "Bombeiro", dica: "Fogo" },
        { palavra: "Advogado", dica: "Lei" },
        { palavra: "Juiz", dica: "Tribunal" },
        { palavra: "Cozinheiro", dica: "Panela" },
        { palavra: "Garçom", dica: "Bandeja" },
        { palavra: "Padeiro", dica: "Pão" },
        { palavra: "Confeiteiro", dica: "Doce" },
        { palavra: "Motorista", dica: "Carro" },
        { palavra: "Piloto", dica: "Avião" },
        { palavra: "Astronauta", dica: "Espaço" },
        { palavra: "Cientista", dica: "Laboratório" },
        { palavra: "Arquiteto", dica: "Desenho" },
        { palavra: "Engenheiro", dica: "Obra" },
        { palavra: "Pedreiro", dica: "Tijolo" },
        { palavra: "Pintor", dica: "Tinta" },
        { palavra: "Eletricista", dica: "Fio" },
        { palavra: "Encanador", dica: "Cano" },
        { palavra: "Mecânico", dica: "Motor" },
        { palavra: "Jornalista", dica: "Notícia" },
        { palavra: "Fotógrafo", dica: "Câmera" },
        { palavra: "Atores", dica: "Teatro" },
        { palavra: "Músico", dica: "Instrumento" },
        { palavra: "Dançarino", dica: "Palco" },
        { palavra: "Cabeleireiro", dica: "Tesoura" },
        { palavra: "Esteticista", dica: "Pele" },
        { palavra: "Costureiro", dica: "Linha" },
        { palavra: "Programador", dica: "Código" },
        { palavra: "Designer", dica: "Arte" },
        { palavra: "Secretário", dica: "Agenda" },
        { palavra: "Vendedor", dica: "Loja" },
        { palavra: "Caixa", dica: "Dinheiro" },
        { palavra: "Carteiro", dica: "Carta" },
        { palavra: "Gari", dica: "Lixo" },
        { palavra: "Segurança", dica: "Porta" },
        { palavra: "Jardineiro", dica: "Planta" },
        { palavra: "Agricultor", dica: "Terra" },
        { palavra: "Pescador", dica: "Rede" },
        { palavra: "Psicólogo", dica: "Conversa" },
        { palavra: "Barbeiro", dica: "Navalha" },
        { palavra: "Marceneiro", dica: "Madeira" },
        { palavra: "Serralheiro", dica: "Ferro" },
        { palavra: "Palhaço", dica: "Circo" },
        { palavra: "Faxineiro", dica: "Limpeza" },
        { palavra: "Contador", dica: "Imposto" },
        { palavra: "Atleta", dica: "Treino" },
        { palavra: "Veterinário", dica: "Clínica" },
        // --- EXPANSÃO ATÉ 100 PROFISSÕES ---
        { palavra: "Farmacêutico", dica: "Remédio" },
        { palavra: "Fisioterapeuta", dica: "Clínica" },
        { palavra: "Nutricionista", dica: "Dieta" },
        { palavra: "Biologista", dica: "Natureza" },
        { palavra: "Arqueólogo", dica: "Fóssil" },
        { palavra: "Historiador", dica: "Passado" },
        { palavra: "Geógrafo", dica: "Mapa" },
        { palavra: "Astrônomo", dica: "Telescópio" },
        { palavra: "Escritor", dica: "Livro" },
        { palavra: "Poeta", dica: "Rima" },
        { palavra: "Tradutor", dica: "Língua" },
        { palavra: "Bibliotecário", dica: "Livros" },
        { palavra: "Diretor de Cinema", dica: "Filme" },
        { palavra: "Roteirista", dica: "História" },
        { palavra: "Dublador", dica: "Voz" },
        { palavra: "Locutor", dica: "Rádio" },
        { palavra: "Humorista", dica: "Piada" },
        { palavra: "Mágico", dica: "Truque" },
        { palavra: "Modelo", dica: "Passarela" },
        { palavra: "Estilista", dica: "Roupa" },
        { palavra: "Maquiador", dica: "Pincel" },
        { palavra: "Manicure", dica: "Unha" },
        { palavra: "Açougueiro", dica: "Carne" },
        { palavra: "Churrasqueiro", dica: "Carne" },
        { palavra: "Barman", dica: "Bebida" },
        { palavra: "Sommelier", dica: "Vinho" },
        { palavra: "Recepcionista", dica: "Balcão" },
        { palavra: "Frentista", dica: "Combustível" },
        { palavra: "Taxista", dica: "Corrida" },
        { palavra: "Entregador", dica: "Moto" },
        { palavra: "Cobrador", dica: "Ônibus" },
        { palavra: "Marinheiro", dica: "Navio" },
        { palavra: "Comissário de Bordo", dica: "Avião" },
        { palavra: "Guia Turístico", dica: "Viagem" },
        { palavra: "Corretor de Imóveis", dica: "Chave" },
        { palavra: "Gerente", dica: "Escritório" },
        { palavra: "Administrador", dica: "Empresa" },
        { palavra: "Publicitário", dica: "Anúncio" },
        { palavra: "Consultor", dica: "Reunião" },
        { palavra: "Auditor", dica: "Controle" },
        { palavra: "Analista de TI", dica: "Computador" },
        { palavra: "Suporte Técnico", dica: "Telefone" },
        { palavra: "Zootecnista", dica: "Fazenda" },
        { palavra: "Zelador", dica: "Prédio" },
        { palavra: "Porteiro", dica: "Guarita" },
        { palavra: "Salva-vidas", dica: "Piscina" },
        { palavra: "Treinador", dica: "Apito" },
        { palavra: "Árbitro", dica: "Cartão" }
    ],
    // ADICIONE ESTA NOVA CATEGORIA AQUI:
    lugares: [
        { palavra: "Casa", dica: "Lar" },
        { palavra: "Escola", dica: "Aluno" },
        { palavra: "Faculdade", dica: "Curso" },
        { palavra: "Hospital", dica: "Médico" },
        { palavra: "Farmácia", dica: "Remédio" },
        { palavra: "Supermercado", dica: "Carrinho" },
        { palavra: "Padaria", dica: "Pão" },
        { palavra: "Restaurante", dica: "Cardápio" },
        { palavra: "Lanchonete", dica: "Lanche" },
        { palavra: "Cafeteria", dica: "Xícara" },
        { palavra: "Shopping", dica: "Lojas" },
        { palavra: "Cinema", dica: "Tela" },
        { palavra: "Teatro", dica: "Palco" },
        { palavra: "Parque", dica: "Árvores" },
        { palavra: "Praça", dica: "Banco" },
        { palavra: "Praia", dica: "Areia" },
        { palavra: "Piscina", dica: "Água" },
        { palavra: "Academia", dica: "Treino" },
        { palavra: "Estádio", dica: "Gramado" },
        { palavra: "Igreja", dica: "Altar" },
        { palavra: "Banco", dica: "Dinheiro" },
        { palavra: "Aeroporto", dica: "Avião" },
        { palavra: "Rodoviária", dica: "Ônibus" },
        { palavra: "Posto de Gasolina", dica: "Bomba" },
        { palavra: "Hotel", dica: "Quarto" },
        { palavra: "Biblioteca", dica: "Livros" },
        { palavra: "Museu", dica: "Arte" },
        { palavra: "Zoológico", dica: "Animais" },
        { palavra: "Delegacia", dica: "Cela" },
        { palavra: "Tribunal", dica: "Juiz" },
        { palavra: "Cemitério", dica: "Túmulo" },
        { palavra: "Salão de Beleza", dica: "Espelho" },
        { palavra: "Barbearia", dica: "Navalha" },
        { palavra: "Oficina Mecânica", dica: "Ferramentas" },
        { palavra: "Pet Shop", dica: "Ração" },
        { palavra: "Clínica Veterinária", dica: "Gato" },
        { palavra: "Estacionamento", dica: "Vaga" },
        { palavra: "Escritório", dica: "Mesa" },
        { palavra: "Fábrica", dica: "Máquinas" },
        { palavra: "Fazenda", dica: "Cercado" },
        { palavra: "Floresta", dica: "Mata" },
        { palavra: "Rio", dica: "Peixe" },
        { palavra: "Mar", dica: "Onda" },
        { palavra: "Montanha", dica: "Pico" },
        { palavra: "Deserto", dica: "Areia" },
        { palavra: "Cozinha", dica: "Fogão" },
        { palavra: "Quarto", dica: "Cama" },
        { palavra: "Banheiro", dica: "Chuveiro" },
        { palavra: "Sala", dica: "Sofá" },
        { palavra: "Lavanderia", dica: "Máquina" },
        { palavra: "Feira", dica: "Barraca" },
        { palavra: "Circo", dica: "Lona" },
        // --- EXPANSÃO ATÉ 100 LUGARES ---
        { palavra: "Metrô", dica: "Trilho" },
        { palavra: "Estação de Trem", dica: "Trilho" },
        { palavra: "Ponto de Ônibus", dica: "Calçada" },
        { palavra: "Porto", dica: "Navio" },
        { palavra: "Pedágio", dica: "Estrada" },
        { palavra: "Garagem", dica: "Carro" },
        { palavra: "Quintal", dica: "Grama" },
        { palavra: "Sacada", dica: "Prédio" },
        { palavra: "Corredor", dica: "Porta" },
        { palavra: "Sótão", dica: "Telhado" },
        { palavra: "Porão", dica: "Escuro" },
        { palavra: "Elevador", dica: "Prédio" },
        { palavra: "Açougue", dica: "Carne" },
        { palavra: "Peixaria", dica: "Peixe" },
        { palavra: "Hortifruti", dica: "Fruta" },
        { palavra: "Floricultura", dica: "Planta" },
        { palavra: "Livraria", dica: "Livros" },
        { palavra: "Papelaria", dica: "Caderno" },
        { palavra: "Banca de Jornal", dica: "Revista" },
        { palavra: "Joalheria", dica: "Ouro" },
        { palavra: "Loja de Roupas", dica: "Cabide" },
        { palavra: "Loja de Sapatos", dica: "Caixa" },
        { palavra: "Sorveteria", dica: "Gelado" },
        { palavra: "Pizzaria", dica: "Forno" },
        { palavra: "Churrascaria", dica: "Espeto" },
        { palavra: "Bar", dica: "Bebida" },
        { palavra: "Boate", dica: "Música" },
        { palavra: "Motel", dica: "Quarto" },
        { palavra: "Cachoeira", dica: "Água" },
        { palavra: "Lago", dica: "Água" },
        { palavra: "Caverna", dica: "Pedra" },
        { palavra: "Vulcão", dica: "Fogo" },
        { palavra: "Ilha", dica: "Mar" },
        { palavra: "Pântano", dica: "Lama" },
        { palavra: "Parque de Diversões", dica: "Brinquedo" },
        { palavra: "Aquário Público", dica: "Peixe" },
        { palavra: "Planetário", dica: "Espaço" },
        { palavra: "Castelo", dica: "Rei" },
        { palavra: "Palácio", dica: "Rei" },
        { palavra: "Farol", dica: "Luz" },
        { palavra: "Quartel", dica: "Farda" },
        { palavra: "Asilo", dica: "Idoso" },
        { palavra: "Orfanato", dica: "Criança" },
        { palavra: "Creche", dica: "Bebê" },
        { palavra: "Estúdio de Tatuagem", dica: "Tinta" },
        { palavra: "Estúdio de Música", dica: "Som" },
        { palavra: "Canil", dica: "Cachorro" }
    ],
    animais: [
        { palavra: "Leão", dica: "Juba" },
        { palavra: "Tigre", dica: "Listras" },
        { palavra: "Elefante", dica: "Tromba" },
        { palavra: "Girafa", dica: "Pescoço" },
        { palavra: "Zebra", dica: "Listras" },
        { palavra: "Cachorro", dica: "Latido" },
        { palavra: "Gato", dica: "Miau" },
        { palavra: "Cavalo", dica: "Casco" },
        { palavra: "Vaca", dica: "Leite" },
        { palavra: "Galinha", dica: "Ovo" },
        { palavra: "Pato", dica: "Bico" },
        { palavra: "Águia", dica: "Garra" },
        { palavra: "Tubarão", dica: "Barbatanas" },
        { palavra: "Baleia", dica: "Oceano" },
        { palavra: "Golfinho", dica: "Salto" },
        { palavra: "Jacaré", dica: "Couro" },
        { palavra: "Cobra", dica: "Veneno" },
        { palavra: "Sapo", dica: "Língua" },
        { palavra: "Tartaruga", dica: "Casco" },
        { palavra: "Macaco", dica: "Banana" },
        { palavra: "Urso", dica: "Mel" },
        { palavra: "Lobo", dica: "Uivo" },
        { palavra: "Raposa", dica: "Cauda" },
        { palavra: "Coelho", dica: "Orelha" },
        { palavra: "Canguru", dica: "Bolsa" },
        { palavra: "Pinguim", dica: "Asa" },
        { palavra: "Urso Polar", dica: "Gelo" },
        { palavra: "Panda", dica: "Bambu" },
        { palavra: "Hipopótamo", dica: "Lama" },
        { palavra: "Rinoceronte", dica: "Chifre" },
        { palavra: "Morcego", dica: "Asa" },
        { palavra: "Rato", dica: "Queijo" },
        { palavra: "Esquilo", dica: "Noz" },
        { palavra: "Castor", dica: "Dente" },
        { palavra: "Camelo", dica: "Deserto" },
        { palavra: "Flamingo", dica: "Rosa" },
        { palavra: "Pavão", dica: "Penas" },
        { palavra: "Coruja", dica: "Olho" },
        { palavra: "Papagaio", dica: "Pena" },
        { palavra: "Beija-flor", dica: "Asa" },
        { palavra: "Formiga", dica: "Doce" },
        { palavra: "Abelha", dica: "Colmeia" },
        { palavra: "Borboleta", dica: "Asa" },
        { palavra: "Aranha", dica: "Teia" },
        { palavra: "Escorpião", dica: "Veneno" },
        { palavra: "Polvo", dica: "Tentáculo" },
        { palavra: "Caranguejo", dica: "Pinça" },
        { palavra: "Ovelha", dica: "Lã" },
        { palavra: "Porco", dica: "Lama" },
        { palavra: "Bode", dica: "Barba" },
        { palavra: "Galo", dica: "Canto" },
        { palavra: "Peru", dica: "Natal" },
        // --- EXPANSÃO ATÉ 100 ANIMAIS ---
        { palavra: "Gamba", dica: "Cheiro" },
        { palavra: "Capivara", dica: "Rio" },
        { palavra: "Tamanduá", dica: "Língua" },
        { palavra: "Preguiça", dica: "Árvore" },
        { palavra: "Tatu", dica: "Casca" },
        { palavra: "Guaxinim", dica: "Máscara" },
        { palavra: "Leopardo", dica: "Pintas" },
        { palavra: "Guepardo", dica: "Veloz" },
        { palavra: "Pantera", dica: "Preto" },
        { palavra: "Hiena", dica: "Riso" },
        { palavra: "Gorila", dica: "Força" },
        { palavra: "Chimpanzé", dica: "Banana" },
        { palavra: "Alce", dica: "Chifre" },
        { palavra: "Veado", dica: "Chifre" },
        { palavra: "Burro", dica: "Orelha" },
        { palavra: "Mula", dica: "Casco" },
        { palavra: "Touro", dica: "Chifre" },
        { palavra: "Búfalo", dica: "Chifre" },
        { palavra: "Carneiro", dica: "Chifre" },
        { palavra: "Avestruz", dica: "Ovo" },
        { palavra: "Cegonha", dica: "Bebê" },
        { palavra: "Urubu", dica: "Preto" },
        { palavra: "Pombo", dica: "Praça" },
        { palavra: "Givana", dica: "Pena" },
        { palavra: "Lagartixa", dica: "Parede" },
        { palavra: "Camaleão", dica: "Cor" },
        { palavra: "Salamandra", dica: "Pele" },
        { palavra: "Água-viva", dica: "Mar" },
        { palavra: "Estrela-do-mar", dica: "Praia" },
        { palavra: "Cavalo-marinho", dica: "Mar" },
        { palavra: "Lula", dica: "Tinta" },
        { palavra: "Lagosta", dica: "Pinça" },
        { palavra: "Camarão", dica: "Mar" },
        { palavra: "Sardinha", dica: "Lata" },
        { palavra: "Mosca", dica: "Asa" },
        { palavra: "Mosquito", dica: "Picada" },
        { palavra: "Pernilongo", dica: "Zumbido" },
        { palavra: "Barata", dica: "Asa" },
        { palavra: "Gafanhoto", dica: "Salto" },
        { palavra: "Grilo", dica: "Canto" },
        { palavra: "Joaninha", dica: "Pintas" },
        { palavra: "Vaga-lume", dica: "Luz" },
        { palavra: "Cigarra", dica: "Canto" },
        { palavra: "Mariposa", dica: "Luz" },
        { palavra: "Minhoca", dica: "Terra" },
        { palavra: "Caracol", dica: "Casco" },
        { palavra: "Carrapato", dica: "Sangue" },
        { palavra: "Sanguessuga", dica: "Sangue" }
    ],
};

const nomesExibicaoCategorias = {
    comida: "Comida",
    famosos: "Famosos",
    objetos: "Objetos do Cotidiano",
    profissao: "Profissão",
    lugares: "Lugares",
    animais: "Animais"
};